// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class PlaceCardComponentHandle extends ffai.ProjectComponentHandle<PlaceCardParams, PlaceCardState> {
  PlaceCardComponentHandle()
    : super(
        name: "PlaceCard",
        key: "Container_5o37ijjv",
        params: const PlaceCardParams(),
        state: const PlaceCardState(),
        widgets: PlaceCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "onTapAction": ffai.json,
          "placeDescription": ffai.string,
          "placeImage": ffai.string,
          "placeLike": ffai.int_,
          "placeName": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? onTapAction = ffai.kUnsetComponentArg,
    Object? placeDescription = ffai.kUnsetComponentArg,
    Object? placeImage = ffai.kUnsetComponentArg,
    Object? placeLike = ffai.kUnsetComponentArg,
    Object? placeName = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(onTapAction)) "onTapAction": onTapAction,
        if (!ffai.isUnsetComponentArg(placeDescription)) "placeDescription": placeDescription,
        if (!ffai.isUnsetComponentArg(placeImage)) "placeImage": placeImage,
        if (!ffai.isUnsetComponentArg(placeLike)) "placeLike": placeLike,
        if (!ffai.isUnsetComponentArg(placeName)) "placeName": placeName,
      },
    );
  }
}

final class PlaceCardParams {
  const PlaceCardParams();
  ffai.ProjectParamHandle get onTapAction =>
      const ffai.ProjectParamHandle(
        name: "onTapAction",
        key: "1tnq0roe",
        typeName: "Action",
      );
  ffai.ProjectParamHandle get placeDescription =>
      const ffai.ProjectParamHandle(
        name: "placeDescription",
        key: "6r3pltmf",
        typeName: "String",
      );
  ffai.ProjectParamHandle get placeImage =>
      const ffai.ProjectParamHandle(
        name: "placeImage",
        key: "8hcpe4hz",
        typeName: "String",
      );
  ffai.ProjectParamHandle get placeLike =>
      const ffai.ProjectParamHandle(
        name: "placeLike",
        key: "zljaudc3",
        typeName: "Integer",
      );
  ffai.ProjectParamHandle get placeName =>
      const ffai.ProjectParamHandle(
        name: "placeName",
        key: "zdgnq3ju",
        typeName: "String",
      );
}

final class PlaceCardState {
  const PlaceCardState();
}

abstract final class PlaceCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_5o37ijjv",
      type: "Container",
      path: "PlaceCard",
      name: "PlaceCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_4odhl9tc",
          type: "Container",
          path: "PlaceCard.children[0]",
          name: "Container Margin",
          triggers: const <String>[
            "ON_TAP",
          ],
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Container_cabayz8k",
              type: "Container",
              path: "PlaceCard.children[0].children[0]",
              name: "Container",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_51hiodad",
                  type: "Row",
                  path: "PlaceCard.children[0].children[0].children[0]",
                  name: "Row",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Image_aal09ewv",
                      type: "Image",
                      path: "PlaceCard.children[0].children[0].children[0].children[0]",
                      name: "Image",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Container_l8p0ni4h",
                      type: "Container",
                      path: "PlaceCard.children[0].children[0].children[0].children[1]",
                      name: "Container",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Column_vimznawn",
                          type: "Column",
                          path: "PlaceCard.children[0].children[0].children[0].children[1].children[0]",
                          name: "Column",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_2c8zxifm",
                              type: "Text",
                              path: "PlaceCard.children[0].children[0].children[0].children[1].children[0].children[0]",
                              name: "Text",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_aufx6gdr",
                              type: "Text",
                              path: "PlaceCard.children[0].children[0].children[0].children[1].children[0].children[1]",
                              name: "Text",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Row_cjvfmkzq",
                              type: "Row",
                              path: "PlaceCard.children[0].children[0].children[0].children[1].children[0].children[2]",
                              name: "Row",
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_2tgah2kk",
                                  type: "Icon",
                                  path: "PlaceCard.children[0].children[0].children[0].children[1].children[0].children[2].children[0]",
                                  name: "Icon",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_pmd4s253",
                                  type: "Text",
                                  path: "PlaceCard.children[0].children[0].children[0].children[1].children[0].children[2].children[1]",
                                  name: "Text",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

