// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final detailPageHandle = ffai.ProjectPageHandle<DetailPageParams, DetailPageState>(
  name: "DetailPage",
  key: "Scaffold_fa9xpm98",
  route: "detail",
  params: const DetailPageParams(),
  state: const DetailPageState(),
  widgets: DetailPageWidgets.tree,
);

final class DetailPageParams {
  const DetailPageParams();
  ffai.ProjectParamHandle get placeId =>
      const ffai.ProjectParamHandle(
        name: "placeId",
        key: "6aud14z6",
        typeName: "Integer",
      );
}

final class DetailPageState {
  const DetailPageState();
  ffai.ProjectStateFieldHandle get isLoading =>
      const ffai.ProjectStateFieldHandle(
        name: "isLoading",
        key: "n6vpxxn4",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get place =>
      const ffai.ProjectStateFieldHandle(
        name: "place",
        key: "ug1k9477",
        typeName: "DataStruct<Place>",
      );
}

abstract final class DetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_fa9xpm98",
      type: "Scaffold",
      path: "DetailPage",
      name: "DetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_o8i67jqc",
            type: "AppBar",
            path: "DetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_wcr37r0z",
                  type: "Text",
                  path: "DetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Place Detail",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_bf2b5r83",
            type: "Container",
            path: "DetailPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_svsj4wbg",
                type: "Column",
                path: "DetailPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_zp7p1lrv",
                    type: "ProgressBar",
                    path: "DetailPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_dq51d7qk",
                    type: "Column",
                    path: "DetailPage.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Image_i1gwcgip",
                        type: "Image",
                        path: "DetailPage.body[0].children[0].children[1].children[0]",
                        name: "Image",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_zcv6okkk",
                        type: "Text",
                        path: "DetailPage.body[0].children[0].children[1].children[1]",
                        name: "PlaceName",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_9qvnrscn",
                        type: "Text",
                        path: "DetailPage.body[0].children[0].children[1].children[2]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_qwfb0eyk",
                        type: "Text",
                        path: "DetailPage.body[0].children[0].children[1].children[3]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

