// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final favoritesPageHandle = ffai.ProjectPageHandle<FavoritesPageParams, FavoritesPageState>(
  name: "FavoritesPage",
  key: "Scaffold_brkp53av",
  route: "favorites",
  params: const FavoritesPageParams(),
  state: const FavoritesPageState(),
  widgets: FavoritesPageWidgets.tree,
);

final class FavoritesPageParams {
  const FavoritesPageParams();
}

final class FavoritesPageState {
  const FavoritesPageState();
}

abstract final class FavoritesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_brkp53av",
      type: "Scaffold",
      path: "FavoritesPage",
      name: "FavoritesPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_k5rkniqf",
            type: "AppBar",
            path: "FavoritesPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_r5kvnze8",
                  type: "Text",
                  path: "FavoritesPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Favorites",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_n2mo9jmw",
            type: "Container",
            path: "FavoritesPage.body[0]",
            name: "FavoritesEmptyState",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_wd2wiwlu",
                type: "Column",
                path: "FavoritesPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Icon_9oftb1oy",
                    type: "Icon",
                    path: "FavoritesPage.body[0].children[0].children[0]",
                    name: "Icon",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_xc3zk1zb",
                    type: "Text",
                    path: "FavoritesPage.body[0].children[0].children[1]",
                    name: "Text",
                    text: "No favorites yet",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_ii7gaqq2",
                    type: "Text",
                    path: "FavoritesPage.body[0].children[0].children[2]",
                    name: "Text",
                    text: "Firestore isn't connected yet - favorites will appear here once it's wired up.",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

