// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homePageHandle = ffai.ProjectPageHandle<HomePageParams, HomePageState>(
  name: "HomePage",
  key: "Scaffold_sk2lcarg",
  route: "",
  params: const HomePageParams(),
  state: const HomePageState(),
  widgets: HomePageWidgets.tree,
);

final class HomePageParams {
  const HomePageParams();
}

final class HomePageState {
  const HomePageState();
  ffai.ProjectStateFieldHandle get isLoading =>
      const ffai.ProjectStateFieldHandle(
        name: "isLoading",
        key: "hlcb76ad",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get likeMultiplier =>
      const ffai.ProjectStateFieldHandle(
        name: "likeMultiplier",
        key: "en1c5rfe",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get places =>
      const ffai.ProjectStateFieldHandle(
        name: "places",
        key: "0ckem0sa",
        typeName: "List<DataStruct<Place>>",
      );
}

abstract final class HomePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_sk2lcarg",
      type: "Scaffold",
      path: "HomePage",
      name: "HomePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_rnfmhxpb",
            type: "AppBar",
            path: "HomePage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_jzckrkkj",
                  type: "Text",
                  path: "HomePage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Tourism App",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_ahpz1ivs",
            type: "Container",
            path: "HomePage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_5iptlhkb",
                type: "Column",
                path: "HomePage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_o6qrs5g1",
                    type: "ProgressBar",
                    path: "HomePage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_1s6qpibn",
                    type: "ListView",
                    path: "HomePage.body[0].children[0].children[1]",
                    name: "ListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_sx4d1mel",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[1].children[0]",
                        name: "PlaceCard",
                        componentName: "PlaceCard",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

