// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final searchPageHandle = ffai.ProjectPageHandle<SearchPageParams, SearchPageState>(
  name: "SearchPage",
  key: "Scaffold_4a89t92k",
  route: "search",
  params: const SearchPageParams(),
  state: const SearchPageState(),
  widgets: SearchPageWidgets.tree,
);

final class SearchPageParams {
  const SearchPageParams();
}

final class SearchPageState {
  const SearchPageState();
  ffai.ProjectStateFieldHandle get hasSearched =>
      const ffai.ProjectStateFieldHandle(
        name: "hasSearched",
        key: "okilb8mi",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isLoading =>
      const ffai.ProjectStateFieldHandle(
        name: "isLoading",
        key: "pn2615bz",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get likeMultiplier =>
      const ffai.ProjectStateFieldHandle(
        name: "likeMultiplier",
        key: "nw0jy",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get results =>
      const ffai.ProjectStateFieldHandle(
        name: "results",
        key: "oj5ezs0m",
        typeName: "List<DataStruct<Place>>",
      );
  ffai.ProjectStateFieldHandle get searchQuery =>
      const ffai.ProjectStateFieldHandle(
        name: "searchQuery",
        key: "gq64wn4i",
        typeName: "String",
      );
}

abstract final class SearchPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_4a89t92k",
      type: "Scaffold",
      path: "SearchPage",
      name: "SearchPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_qp7y0ufw",
            type: "AppBar",
            path: "SearchPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_wg520iha",
                  type: "Text",
                  path: "SearchPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Search",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_rsashoy9",
            type: "Container",
            path: "SearchPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_e6bz8765",
                type: "Column",
                path: "SearchPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "TextField_suvtbjlw",
                    type: "TextField",
                    path: "SearchPage.body[0].children[0].children[0]",
                    name: "TextField",
                    text: "Search destinations...",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                      "ON_TEXTFIELD_SUBMIT",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_ko0w923m",
                    type: "ProgressBar",
                    path: "SearchPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_k66jf53f",
                    type: "ListView",
                    path: "SearchPage.body[0].children[0].children[2]",
                    name: "ListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_q5jp6u92",
                        type: "Container",
                        path: "SearchPage.body[0].children[0].children[2].children[0]",
                        name: "PlaceCard",
                        componentName: "PlaceCard",
                        triggers: const <String>[
                          "CALLBACK",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

