// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class ApiGroups {
  static const tourismApi = "TourismApi";
  static const all = <String>[
    "TourismApi",
  ];
}

abstract final class ActionBlocks {
  static const all = <String>[
  ];
}

