// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/place_card.dart' show PlaceCardComponentHandle;

abstract final class Components {
  static final placeCard = PlaceCardComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    placeCard,
  ];
}
