// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/detail_page.dart' show detailPageHandle;
import 'pages/favorites_page.dart' show favoritesPageHandle;
import 'pages/home_page.dart' show homePageHandle;
import 'pages/search_page.dart' show searchPageHandle;

abstract final class Pages {
  static final detailPage = detailPageHandle;
  static final favoritesPage = favoritesPageHandle;
  static final homePage = homePageHandle;
  static final searchPage = searchPageHandle;
  static final all = <ffai.ProjectPageHandle>[
    detailPage,
    favoritesPage,
    homePage,
    searchPage,
  ];
}
