// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class Project {
  static const id = "tourism-app-lv2d29";
  static const name = "Tourism App";
  static const sdkMetaVersion = 2;
}
