// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'dart:collection';

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static final ffai.StructHandle place = ffai.StructHandle(
    "Place",
    <String, ffai.DslType>{
      "address": ffai.string,
      "description": ffai.string,
      "id": ffai.int_,
      "image": ffai.string,
      "latitude": ffai.double_,
      "like": ffai.int_,
      "longitude": ffai.double_,
      "name": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle placeDetailResponse = ffai.StructHandle(
    "PlaceDetailResponse",
    <String, ffai.DslType>{
      "error": ffai.bool_,
      "message": ffai.string,
      "places": Structs.place,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle placeListResponse = ffai.StructHandle(
    "PlaceListResponse",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "error": ffai.bool_,
      "message": ffai.string,
      "places": ffai.listOf(Structs.place),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle placeSearchResponse = ffai.StructHandle(
    "PlaceSearchResponse",
    <String, ffai.DslType>{
      "error": ffai.bool_,
      "message": ffai.string,
      "places": ffai.listOf(Structs.place),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final all = <ffai.StructHandle>[
    place,
    placeDetailResponse,
    placeListResponse,
    placeSearchResponse,
  ];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static const all = <ffai.ProjectTableHandle>[];
}

abstract final class CustomCode {
  static const functions = <String>[
  ];
  static const actions = <String>[
    "inflateLikeCounts",
  ];
  static const widgets = <String>[
  ];
}

